version: "3"
services:
  app:
    build: .
    ports:
      - "5001:5001"
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - "3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: resepkita
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/:ro